<?php

/**
 * Created by PhpStorm.
 * User: Kyle
 * Date: 4/2/2016
 * Time: 11:51 AM
 */
class IndexTest extends \PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @runInSeparateProcess
     */
    public function testRenderBodyContent()
    {
        $Index = new \mqtchums\Index();

        $reflection = new \ReflectionObject($Index);
        $method = $reflection->getMethod('RenderBodyContent');
        $method->setAccessible(true);

        $result = $method->invokeArgs($Index, []);
        $this->assertEquals('Welcome to MQTCHUMS.org!', $result, 'Expecting a static string response, it should match a static string.');


        $output = $this->getActualOutput();
        $this->assertContains('Welcome to MQTCHUMS.org!', $output, 'expecting the static string to make it to the screen!');
        $this->assertContains('<title>MQTCHUMS</title>', $output, 'Validating the title of the website');

    }

}
